In [1]:
%pip install tensorflow_hub
%pip install tensorflow_text

     |████████████████████████████████| 4.9 MB 7.0 MB/s 
     |████████████████████████████████| 462 kB 49.6 MB/s 


In [2]:
import tensorflow_hub as hub
import tensorflow_text as text

In [3]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [4]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [6]:
text_test = ["nice movie indeed", "I love python programming"]
text_preprocessed = bert_preprocess_model(text_test)
# text_preprocessed

In [7]:
bert_model = hub.KerasLayer(encoder_url)
bert_result = bert_model(text_preprocessed)
bert_result.keys()

dict_keys(['encoder_outputs', 'sequence_output', 'default', 'pooled_output'])

In [8]:
bert_result["pooled_output"] # is embedding for the entire sentence

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411912,  0.49769545, ...,  0.24465251,
        -0.47334474,  0.8175869 ],
       [-0.917123  , -0.4793517 , -0.7865697 , ..., -0.6175173 ,
        -0.7102685 ,  0.92184293]], dtype=float32)>

In [9]:
bert_result["sequence_output"] # is individual word embedding vectors

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292052,  0.08567828,  0.14476834, ..., -0.0967709 ,
          0.08722137,  0.07711098],
        [ 0.17839345, -0.19006056,  0.5034947 , ..., -0.05869841,
          0.327171  , -0.15578514],
        [ 0.18701436, -0.4338877 , -0.48875144, ..., -0.15502788,
          0.00145161, -0.24470939],
        ...,
        [ 0.12083046,  0.12884249,  0.46453536, ...,  0.07375503,
          0.17441958,  0.16522127],
        [ 0.07967918, -0.01190616,  0.502254  , ...,  0.13777718,
          0.21002227,  0.0062459 ],
        [-0.07212696, -0.28303486,  0.59033376, ...,  0.47551915,
          0.16668484, -0.08920329]],

       [[-0.07900572,  0.36335105, -0.21101584, ..., -0.17183706,
          0.16299748,  0.6724269 ],
        [ 0.27883518,  0.43716267, -0.35764715, ..., -0.04463615,
          0.38315132,  0.5887984 ],
        [ 1.2037678 ,  1.0727018 ,  0.48408744, ...,  0.2492101 ,
          0.40730923,  0.40481845],
        ...,

In [10]:
print(len(bert_result["encoder_outputs"]))# is embedding for the entire sentence
# bert_result["encoder_outputs"] # is embedding for the entire sentence

12


[<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901428,  0.0064474 , -0.03614964, ...,  0.04999623,
           0.06149206, -0.02657545],
         [ 1.1753383 ,  1.2140785 ,  1.1569983 , ...,  0.11634364,
          -0.35855377, -0.40490168],
         [ 0.03859018,  0.5386998 , -0.21089801, ...,  0.21858177,
           0.7260169 , -1.1158607 ],
         ...,
         [-0.07587013, -0.254219  ,  0.7075511 , ...,  0.50541985,
          -0.18878691,  0.15028363],
         [-0.16066611, -0.2808967 ,  0.57597065, ...,  0.5275853 ,
          -0.11141387,  0.02887536],
         [-0.04428155, -0.20279603,  0.5909355 , ...,  0.8133835 ,
          -0.39075804, -0.02601746]],
 
        [[ 0.1890358 ,  0.02752538, -0.06513737, ..., -0.00620209,
           0.15053886,  0.03165445],
         [ 0.5916147 ,  0.75891393, -0.0724067 , ...,  0.6190396 ,
           0.82928896,  0.1616196 ],
         [ 1.4460826 ,  0.44602647,  0.40990263, ...,  0.48255885,
           0.6269116 ,  0.13